core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('project/', include('project.urls', namespace='project')),

    path('about', views.about, name='about'),
    path('service', views.service, name='service'),    
    path('<slug:slug>/', views.ServiceDetail.as_view(), name='service_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    path('<slug:slug>/', views.project_detail, name='project_detail'),
]

home/models.py
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe

class Company(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True,max_length=100)
    phone = models.CharField(blank=True,max_length=15)
    mobile = models.CharField(blank=True,max_length=15)
    email = models.CharField(blank=True,max_length=50)
    icon = models.ImageField(blank=True,upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    youtube = models.CharField(blank=True, max_length=50)
    status=models.CharField(max_length=10,choices=STATUS)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Company'

    def __str__(self):
        return self.title


class Service(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=50)
    keywords = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=60, blank=True)
    icon = models.CharField(max_length=20)
    detail = models.CharField(max_length=255)
    short_detail = models.CharField(max_length=255)
    status = models.CharField(max_length=10, choices=STATUS)
    portfolio_title = models.CharField(max_length=50)
    portfolio_image = models.ImageField(upload_to='images/')
    portfolio_alt = models.CharField(max_length=60, blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Services'
    
    def get_absolute_url(self):
        return reverse('service_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

class About(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=50)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    detail = models.CharField(max_length=300)
    short_detail = models.CharField(max_length=300)
    image=models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=60, blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'About'

    def __str__(self):
        return self.title

class Clients(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=60, blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Clients'

    def __str__(self):
        return self.name

class Team(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    name = models.CharField(max_length=50)
    designation = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=60, blank=True)
    facebook = models.URLField(max_length=100)
    twitter = models.URLField(max_length=100)
    instagram = models.URLField(max_length=100)
    linkedin = models.URLField(max_length=100)
    status = models.CharField(max_length=10, choices=STATUS)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    
    ## Method in creating a fake table in read-only mode
    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url)) #defined like this - from django.utils.safestring import mark_safe

    image_tag.short_description = 'Image'


class Strategy(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    mission = models.CharField(max_length=250)
    vision = models.CharField(max_length=250)
    quality = models.CharField(max_length=250)
    status = models.CharField(max_length=10, choices=STATUS)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Strategy'

    def __str__(self):
        return self.mission

project/models.py
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe

from home.models import Service

class Project(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )

    service = models.ForeignKey(Service, related_name='project', on_delete=models.CASCADE) #many to one relation with Service
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    image=models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=60, blank=True)
    client = models.CharField(max_length=50)
    launched = models.CharField(max_length=50)
    demands = models.CharField(max_length=50)
    detail = models.CharField(max_length=255)
    short_detail = models.CharField(max_length=255)
    video_link = models.CharField(max_length=20)
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(max_length=255)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Projects'
        ordering = ('-created',)
    
    def get_absolute_url(self):
        return reverse('project:project_detail', args=[self.slug])
    
    def __str__(self):
        return self.title


## Method in creating a fake table in read-only mode
    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url)) #defined like this - from django.utils.safestring import mark_safe

    image_tag.short_description = 'Image'

    
class Images(models.Model):
    project=models.ForeignKey(Project, on_delete=models.CASCADE) #many to one relation with Product
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=60)

    class Meta:
        verbose_name_plural = 'Images'

    def __str__(self):
        return self.title


class Gallery(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )

    service = models.ForeignKey(Service, related_name='gallery', on_delete=models.CASCADE) #many to one relation with Service
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    image=models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=60, blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Gallery'

    def __str__(self):
        return self.title


## Method in creating a fake table in read-only mode
    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url)) #defined like this - from django.utils.safestring import mark_safe

    image_tag.short_description = 'Image'

home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic

from .models import About, Clients, Company, Service, Strategy
from project.models import Project

def home(request):
    company = Company.objects.get(pk=1)
    about = About.objects.all()
    service = Service.objects.order_by('-created')[:4]
    projects = Project.objects.order_by('-created')[:6]
    clients = Clients.objects.all()
    return render(request, 'index.html', {'company': company, 'about': about, 'service': service, 'projects': projects, 'clients': clients})


def about(request):
    company = Company.objects.get(pk=1)
    about = About.objects.all()
    clients = Clients.objects.all()
    return render(request, 'about.html', {'company': company, 'about': about, 'clients': clients})


def service(request):
    service = Service.objects.all()
    return render(request, 'service.html', {'service': service})



class ServiceDetail (generic.DetailView):
    model = Service
    template_name = 'service_detail.html'

project/views.py
from django.shortcuts import get_object_or_404, render

from .models import Project

def all_projects(request):
    projects = Project.objects.all()
    return render(request, 'project.html', {'projects': projects})


def project_detail(request, slug):
    project = get_object_or_404(Project, slug=slug)
    return render(request, 'project_detail.html', {'project': project})

home/templates/navbar.html
{% load static %}

<nav class="mainmenu-eight main-header">
    <div class="auto-container">
        <div class="nav-outer mainmenu-eight__inner ">
            <div class="mainmenu-eight__left">
                <a href="{% url 'home:home' %}">
                    <img src="{% static 'images/update-01-10-2021/synkisol-logo.png' %}" height="50px" width="300px"
                        alt="Synkisol Synergy Solution Logo">
                </a>
                <div class="mobile-nav-toggler"><span class="icon flaticon-menu-2"></span><span
                        class="txt">Menu</span></div>

            </div><!-- /.mainmenu-eight__left -->
            <nav class="main-menu navbar-expand-md navbar-light">
                <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
                    <ul class="navigation clearfix">
                        <li><a href="{% url 'home:home' %}">Home</a>
                        </li>
                        <li><a href="{% url 'about' %}">About</a>
                        </li>
                        <li class="dropdown"><a href="{% url 'service' %}">Services</a>
                            {% comment %} <ul>
                            {% for rs in service %}
                                <li><a href="{% url 'service_detail' rs.slug %}">{{ rs.title| title }}</a></li>
                            {% endfor %}
                            </ul> {% endcomment %}
                        </li>
                        <li><a href="{% url 'project:all_projects' %}">Portfolio</a>
                        </li>
                        <li><a href="contact.html">Contact</a>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="mainmenu-eight__right">
                <!-- <div class="search-btn mainmenu-eight__search">
                    <button type="button" class="theme-btn search-toggler"><span
                            class="flaticon-magnifying-glass"></span></button>
                </div> -->

                <a href="tel:+254742690110" class="mainmenu-eight__call">
                    <span class="mainmenu-eight__call__icon">
                        <i class="flaticon-phone"></i>
                    </span><!-- /.mainmenu-eight__call__icon -->
                    <span class="mainmenu-eight__call__text">
                        Have any questions? <br>
                        Free: <strong>+254 742 690 110</strong>
                    </span><!-- /.mainmenu-eight__call__text -->
                </a>

            </div><!-- /.mainmenu-eight__right -->
        </div><!-- /.mainmenu-eight__inner -->
    </div><!-- /.auto-container -->
</nav><!-- /.mainmenu-eight -->
</header><!-- /.header-eight -->

home/templates/project.html
{% extends 'base.html' %}

{% block title %} Project {% endblock %}
{% block keywords %} Project Keywords {% endblock %}
{% block description %} Project Description {% endblock %}

{% block content %}

{% load static %}

<!-- Banner Section -->
<section class="page-banner">
    <div class="image-layer" style="background-image:url({% static 'images/background/image-7.jpg' %});"></div>
    <div class="shape-1"></div>
    <div class="shape-2"></div>
    <div class="banner-inner">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <h1>Portfolio</h1>
                <div class="page-nav">
                    <ul class="bread-crumb clearfix">
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li class="active">Portfolio</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End Banner Section -->

<!-- Gallery Section -->
<section class="gallery-section">
    <div class="auto-container">
        <!--MixitUp Galery-->
        <div class="mixitup-gallery">
            <div class="filter-list row">
                <!-- Gallery Item -->
                {% for rs in projects %}
                <div class="gallery-item mix all web-design col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <figure class="image"><img src="{{ rs.image.url }}" height="370px" width="426px" alt="{{ rs.alt }}"></figure>
                        <a href="{{ rs.image.url }}" class="lightbox-image overlay-box"
                            data-fancybox="gallery"></a>
                        <div class="cap-box">
                            <div class="cap-inner">
                                <div class="cat"><span>{{ rs.service }}</span></div>
                                <div class="title">
                                    <h5><a href="{{ rs.get_absolute_url }}">{{ rs.title }}</a></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            {% comment %} <div class="more-box">
                <a class="theme-btn btn-style-one" href="portfolio.html">
                    <i class="btn-curve"></i>
                    <span class="btn-title">Load more work</span>
                </a>
            </div> {% endcomment %}
        </div>

    </div>
</section>

{% endblock %}

home/templates/project_detail.html
{% extends 'base.html' %}

{% block title %} {{ project.title }} {% endblock %}
{% block keywords %} Project Details Keywords {% endblock %}
{% block description %} Project Details Description {% endblock %}

{% block content %}

{% load static %}

<!-- Banner Section -->
<section class="page-banner">
    <div class="image-layer" style="background-image:url({% static 'images/background/image-7.jpg' %});"></div>
    <div class="shape-1"></div>
    <div class="shape-2"></div>
    <div class="banner-inner">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <h1>Portfolio</h1>
                <div class="page-nav">
                    <ul class="bread-crumb clearfix">
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li><a href="{% url 'project:all_projects' %}">Projects</a></li>
                        <li class="active">{{project.title}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End Banner Section -->

<!-- Project Single -->
<section class="project-single style-two">
    <div class="auto-container">
        <figure class="image-box">
            <a href="{{ project.image.url }}" class="lightbox-image" data-fancybox="gallery"><img
                    src="{{ project.image.url }}" alt="{{ project.alt }}"></a>
        </figure>
        <div class="text-content">
            <div class="row clearfix">
                <!-- Text COl -->
                <div class="text-col col-lg-8 col-md-12 col-sm-12">
                    <div class="inner">
                        <h5>{{ project.title }}</h5>
                        <p>{{ project.detail }}</p>
                    </div>
                </div>
                <!-- Text COl -->
                <div class="text-col col-lg-4 col-md-12 col-sm-12">
                    <div class="inner">
                        <ul class="info">
                            <li><strong>Clients:</strong> <br>{{ project.client }}</li>
                            <li><strong>Category:</strong> <br>{{ project.service }}</li>
                            <li><strong>Date:</strong> <br>{{ project.launched }}</li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

<section class="portfolio-details-video">
    <div class="auto-container">
        <!-- <div class="portfolio-details-video__thumbnail">
            <img src="{% static 'images/update-26-02-2021/resources/portfolio-d-video-1.jpg' %}" alt="">
            <div class="vid-link">
                <a href="https://www.youtube.com/watch?v=Get7rqXYrbQ" class="lightbox-image">
                    <div class="icon"><span class="flaticon-play-button-1"></span><i class="ripple"></i></div>
                </a>
            </div>
        </div> -->
    </div><!-- /.auto-container -->
</section><!-- /.portfolio-details-video -->

<!-- <section class="portfolio-details-summery">
    <div class="auto-container">
        <div class="row">
            <div class="col-md-6">
                <h3 class="portfolio-details-summery__heading">Conclusion</h3>
                
                <p class="portfolio-details-summery__text">
                    Tincidunt elit magnis nulla facilisis sagittis sapien in nunc amet ultrices dolores sit
                    ipsum velit quet massa fringilla leo orci nc amet ultrices, dolores sit ipsum velit massa
                    fringilla leo.
                </p>
            </div>
            <div class="col-md-6">
                <h3 class="portfolio-details-summery__heading">result</h3>
                
                <p class="portfolio-details-summery__text">
                    Tincidunt elit magnis nulla facilisis sagittis sapien in nunc amet ultrices dolores sit
                    ipsum velit quet massa fringilla leo orci nc amet ultrices, dolores sit ipsum velit massa
                    fringilla leo.
                </p>
            </div>
        </div>
    </div>
</section> -->

<div class="post-control">
    <div class="auto-container">
        <div class="inner clearfix">
            <div class="control prev"><a href="#"><span class="fa fa-angle-left"></span> &nbsp; Previous</a>
            </div>
            <div class="control next"><a href="#">Next &nbsp;<span class="fa fa-angle-right"></span></a></div>
        </div>
    </div>
</div>

<!-- Similar Section -->
<!-- <section class="gallery-section similar-gallery">
    <div class="auto-container">
        <div class="sec-title centered">
            <h2>Similar work<span class="dot">.</span></h2>
        </div>
        <div class="row clearfix">
            
            <div class="gallery-item col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <figure class="image"><img src="images/gallery/4.jpg" alt=""></figure>
                    <a href="images/gallery/4.jpg" class="lightbox-image overlay-box" data-fancybox="gallery"></a>
                    <div class="cap-box">
                        <div class="cap-inner">
                            <div class="cat"><span>Graphic</span></div>
                            <div class="title">
                                <h5><a href="portfolio-single.html">Fimlor Experience</a></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            
            <div class="gallery-item col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <figure class="image"><img src="images/gallery/5.jpg" alt=""></figure>
                    <a href="images/gallery/5.jpg" class="lightbox-image overlay-box" data-fancybox="gallery"></a>
                    <div class="cap-box">
                        <div class="cap-inner">
                            <div class="cat"><span>Graphic</span></div>
                            <div class="title">
                                <h5><a href="portfolio-single.html">Fimlor Experience</a></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            
            <div class="gallery-item col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <figure class="image"><img src="images/gallery/6.jpg" alt=""></figure>
                    <a href="images/gallery/6.jpg" class="lightbox-image overlay-box" data-fancybox="gallery"></a>
                    <div class="cap-box">
                        <div class="cap-inner">
                            <div class="cat"><span>Graphic</span></div>
                            <div class="title">
                                <h5><a href="portfolio-single.html">Fimlor Experience</a></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</section> -->

{% endblock %}

home/templates/service.html
{% extends 'base.html' %}

{% block title %} Service {% endblock %}
{% block keywords %} Project Keywords {% endblock %}
{% block description %} Project Description {% endblock %}

{% block content %}

{% load static %}

		<!-- Banner Section -->
		<section class="page-banner">
			<div class="image-layer" style="background-image:url({% static 'images/background/image-7.jpg' %});"></div>
			<div class="shape-1"></div>
			<div class="shape-2"></div>
			<div class="banner-inner">
				<div class="auto-container">
					<div class="inner-container clearfix">
						<h1>Services</h1>
						<div class="page-nav">
							<ul class="bread-crumb clearfix">
								<li><a href="{% url 'home:home' %}">Home</a></li>
								<li class="active">Services</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--End Banner Section -->

		<section class="service-nine">
			<div class="auto-container">
				<div class="row">
                    {% for rs in service %}
					<div class="col-md-6 col-lg-4">
						<div class="service-nine__card">
							<div class="service-nine__card__inner">
								<div class="service-nine__image">
									<img src="{{ rs.image.url }}" alt="{{ rs.alt }}">
								</div><!-- /.service-nine__image -->
								<div class="service-nine__content">
									<div class="service-nine__icon">
										<i class="flaticon-responsive"></i>
									</div><!-- /.service-nine__icon -->
									<h3 class="service-nine__title">
										<a href="{% url 'service_detail' rs.slug %}">{{ rs.title }}</a>
									</h3><!-- /.service-nine__title -->
									<p class="service-nine__text">{{ rs.short_detail }}</p><!-- /.service-nine__text -->
									<a href="ui-designing.html" class="service-nine__link"><i
											class="fa fa-angle-right"></i></a>
								</div><!-- /.service-nine__content -->
							</div><!-- /.service-nine__card__inner -->
						</div><!-- /.service-nine__card -->
					</div><!-- /.col-md-6 col-lg-4 -->
                    {% endfor %}
				</div><!-- /.row -->
			</div><!-- /.auto-container -->
		</section><!-- /.service-nine -->

{% endblock %}

home/templates/service_detail.html
{% extends 'base.html' %}

{% block title %} {{service.title}} {% endblock %}
{% block keywords %} {{ company.keywords }} {% endblock %}
{% block description %} {{ company.description }} {% endblock %}

{% block content %}

{% load static %}

<!-- Banner Section -->
        <section class="page-banner">
            <div class="image-layer" style="background-image:url({% static 'images/background/image-7.jpg' %});"></div>
            <div class="shape-1"></div>
            <div class="shape-2"></div>
            <div class="banner-inner">
                <div class="auto-container">
                    <div class="inner-container clearfix">
                        <h1>{{service.title}}</h1>
                        <div class="page-nav">
                            <ul class="bread-crumb clearfix">
                                <li><a href="{% url 'home:home' %}">Home</a></li>
                                <li><a href="{% url 'service' %}">Services</a></li>
                                <li class="active">{{service.title}}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--End Banner Section -->

        <div class="sidebar-page-container">
            <div class="auto-container">
                <div class="row clearfix">

                    <!--Content Side-->
                    <div class="content-side col-lg-8 col-md-12 col-sm-12">
                        <div class="service-details">
                            <div class="main-image image">
                                <img src="{{service.image.url}}" alt="{{service.alt}}">
                            </div>
                            <div class="text-content">
                                <h3>{{service.title}}</h3>
                                <p>{{service.detail | safe}}</p> 
                            </div>
                        </div>
                    </div>

                    <!--Sidebar Side-->
                    <div class="sidebar-side col-lg-4 col-md-12 col-sm-12">
                        <aside class="sidebar blog-sidebar">

                            <!-- <div class="sidebar-widget services">
                                <div class="widget-inner">
                                    <div class="sidebar-title">
                                        <h4>All Services</h4>
                                    </div>
                                    <ul>
                                        <li><a href="web-development.html">Website Development</a></li>
                                        <li><a href="graphic-designing.html">Graphic Designing</a></li>
                                        <li><a href="digital-marketing.html">Digital Marketing</a></li>
                                        <li><a href="seo.html">SEO & Content Writting</a></li>
                                        <li><a href="app-development.html">App Development</a></li>
                                        <li><a href="ui-designing.html">UI/UX Designing</a></li>
                                    </ul>
                                </div>
                            </div> -->

                            <div class="sidebar-widget call-up">
                                <div class="widget-inner">
                                    <div class="sidebar-title">
                                        <h4>need of our help?</h4>
                                    </div>
                                    <div class="text">You can contact our offices, and we will assist you.</div>
                                    <div class="phone"><a href="tel:+254742690110"><span
                                                class="icon flaticon-call"></span>+254 742 690 110</a></div>
                                </div>
                            </div>


                        </aside>
                    </div>

                </div>
            </div>
        </div>

        <!-- Call To Section -->
        <section class="call-to-section-two alternate">
            <div class="auto-container">
                <div class="inner clearfix">
                    <h2>We&#39;re Ready to Bring Bigger <br>& Stronger Projects</h2>
                    <div class="link-box">
                        <a class="theme-btn btn-style-two" href="#">
                            <i class="btn-curve"></i>
                            <span class="btn-title">Contact with us</span>
                        </a>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}

home/templates/topheader.html
{% load static %}

<header class="header-eight">
    <div class="header-eight__topbar">
        <div class="auto-container">
            <ul class="header-eight__topbar__info">
                <li>
                    <i class="flaticon-email-2"></i>
                    <a href="mailto:info@synkisol.co.ke">info@synkisol.co.ke</a>
                </li>
                <li>
                    <i class="flaticon-pin-1"></i>
                    Nairobi, Kenya
                </li>
            </ul><!-- /.header-eight__info -->
            <div class="header-eight__topbar__right">
                <p>Welcome to Synkisol Synergy Solutions.</p>
                <div class="header-eight__topbar__social">
                    <!-- <a href="#" class="fab fa-twitter"></a> -->
                    <a href="https://www.facebook.com/synkisol" target="_blank" class="fab fa-facebook"></a>
                    <a href="#" target="_blank" class="fab fa-linkedin"></a>
                    <a href="https://www.instagram.com/synkisol" target="_blank" class="fab fa-instagram"></a>
                </div><!-- /.header-eight__social -->
            </div><!-- /.header-eight__right -->
        </div><!-- /.auto-container -->
    </div><!-- /.header-eight__topbar -->